Controllers/AboutController.cs
using LifeSure.Models.DataModels;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LifeSure.Controllers
{
    public class AboutController : Controller
    {
        private readonly LifeSureDbEntities db = new LifeSureDbEntities();
        public ActionResult Index()
        {
            var aboutList = db.TblAbout.ToList();
            return View(aboutList);
        }

        [HttpGet]
        public ActionResult AddAbout()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddAbout(TblAbout about)
        {
            if (ModelState.IsValid)
            {
                db.TblAbout.Add(about);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(about);
        }

        public ActionResult Delete(int id)
        {
            var about = db.TblAbout.Find(id);
            if(about != null)
            {
                db.TblAbout.Remove(about);
                db.SaveChanges();
            }
            return RedirectToAction("Index", "Admin");
        }

        [HttpGet]
        public ActionResult UpdateAbout(int id)
        {
            var about = db.TblAbout.Find(id);
            if (about == null)
            {
                return HttpNotFound();
            }
            return View(about);
        }

        [HttpPost]
        public ActionResult UpdateAbout(TblAbout about)
        {
            if (ModelState.IsValid)
            {
                db.Entry(about).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(about);
        }
    }
}

Controllers/ContactController.cs
using LifeSure.Models.DataModels;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LifeSure.Controllers
{
    public class ContactController : Controller
    {
        private readonly LifeSureDbEntities db = new LifeSureDbEntities();
        public ActionResult Index()
        {
            var contactList = db.TblContact.ToList();
            return View(contactList);
        }

        [HttpGet]
        public ActionResult AddContact()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddContact(TblContact contact)
        {
            if (ModelState.IsValid)
            {
                db.TblContact.Add(contact);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(contact);
        }

        public ActionResult Delete(int id)
        {
            var contact = db.TblContact.Find(id);
            if (contact != null)
            {
                db.TblContact.Remove(contact);
                db.SaveChanges();
            }
            return RedirectToAction("Index", "Admin");
        }

        [HttpGet]
        public ActionResult UpdateContact(int id)
        {
            var contact = db.TblContact.Find(id);
            if (contact == null)
            {
                return HttpNotFound();
            }
            return View(contact);
        }

        [HttpPost]
        public ActionResult UpdateContact(TblContact contact)
        {
            if (ModelState.IsValid)
            {
                db.Entry(contact).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(contact);
        }
    }
}

Controllers/FaqController.cs
using LifeSure.Models.DataModels;
using LifeSure.Models.ViewModels;
using LifeSure.Services;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace LifeSure.Controllers
{
    public class FaqController : Controller
    {
        private readonly RapidApiChatGptService _chatService;
        private readonly LifeSureDbEntities db = new LifeSureDbEntities();

        public FaqController()
        {
            string apiKey = ConfigurationManager.AppSettings["ChatGptRapidApi_Key"];
            _chatService = new RapidApiChatGptService(apiKey);
        }

        [HttpGet]
        public ActionResult Generate()
        {
            return View(new FaqViewModel());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Generate(FaqViewModel model, string submitType)
        {
            if (submitType == "SoruOlustur")
            {
                var promptForQuestion = $"Sadece kısa ve net bir soru oluştur, başka bir açıklama yapma: {model.Prompt}";
                var question = await _chatService.SendMessageAsync(promptForQuestion);
                model.Question = question;

                var entity = new TblFaq { FaqQuestion = question };
                db.TblFaq.Add(entity);
                db.SaveChanges();
            }
            else if (submitType == "CevapOlustur")
            {
                // 1. En son eklenen soruyu al
                var entity = db.TblFaq.OrderByDescending(x => x.FaqId).FirstOrDefault();
                if (entity != null)
                {
                    // 2. Soruya göre cevap üret
                    var promptForAnswer = $"Sadece soruya cevap ver, tekrar soruyu veya açıklamayı yazma: {entity.FaqQuestion}";
                    var answer = await _chatService.SendMessageAsync(promptForAnswer);
                    model.Answer = answer;

                    // 3. Cevabı veritabanına yaz
                    entity.FaqAnsver = answer;
                    db.SaveChanges();
                }
            }

            ModelState.Clear();
            return View("Generate", model);
        }



    }
}

Controllers/TeamController.cs
using LifeSure.Models.DataModels;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LifeSure.Controllers
{
    public class TeamController : Controller
    {
        private readonly LifeSureDbEntities db = new LifeSureDbEntities();
        public ActionResult Index()
        {
            var teamList = db.TblEmployee.ToList();
            return View(teamList);
        }

        [HttpGet]
        public ActionResult AddTeam()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddTeam(TblEmployee employee)
        {
            if (ModelState.IsValid)
            {
                db.TblEmployee.Add(employee);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(employee);
        }

        public ActionResult Delete(int id)
        {
            var employee = db.TblEmployee.Find(id);
            if (employee != null)
            {
                db.TblEmployee.Remove(employee);
                db.SaveChanges();
            }
            return RedirectToAction("Index", "Admin");
        }

        [HttpGet]
        public ActionResult UpdateTeam(int id)
        {
            var employee = db.TblEmployee.Find(id);
            if (employee == null)
            {
                return HttpNotFound();
            }
            return View(employee);
        }

        [HttpPost]
        public ActionResult UpdateTeam(TblEmployee employee)
        {
            if (ModelState.IsValid)
            {
                db.Entry(employee).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(employee);
        }
    }
}

Views/Admin/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="row">
    <div class="col-xl-3 mb-30">
        <div class="card-box height-100-p widget-style1">
            <a href="@Url.Action("Index", "About")" style="text-decoration: none; color: inherit;">
                <div class="d-flex align-items-center justify-content-center" style="height: 100px;">
                    <div class="mr-3 text-primary">
                        <i class="fa fa-info-circle fa-3x"></i>
                    </div>
                    <div class="widget-data">
                        <div style="font-size: 1.5rem; font-weight: 600;">Hakkımızda</div>
                    </div>
                </div>
            </a>
        </div>
    </div>

    <div class="col-xl-3 mb-30">
        <div class="card-box height-100-p widget-style1">
            <a href="@Url.Action("GenerateImage", "ServiceImage")" style="text-decoration: none; color: inherit;">
                <div class="d-flex align-items-center justify-content-center" style="height: 100px;">
                    <div class="mr-3 text-success">
                        <i class="fa fa-cogs fa-3x"></i>
                    </div>
                    <div class="widget-data">
                        <div style="font-size: 1.5rem; font-weight: 600;">Hizmetler</div>
                    </div>
                </div>
            </a>
        </div>
    </div>

    <div class="col-xl-3 mb-30">
        <div class="card-box height-100-p widget-style1">
            <a href="@Url.Action("Generate", "Faq")" style="text-decoration: none; color: inherit;">
                <div class="d-flex align-items-center justify-content-center" style="height: 100px;">
                    <div class="mr-3 text-warning">
                        <i class="fa fa-question-circle fa-3x"></i>
                    </div>
                    <div class="widget-data">
                        <div style="font-size: 1.5rem; font-weight: 600;">SSS</div>
                    </div>
                </div>
            </a>
        </div>
    </div>


    <div class="col-xl-3 mb-30">
        <div class="card-box height-100-p widget-style1">
            <a href="@Url.Action("Index", "Contact")" style="text-decoration: none; color: inherit;">
                <div class="d-flex align-items-center justify-content-center" style="height: 100px;">
                    <div class="mr-3 text-primary">
                        <i class="fa fa-bell fa-3x"></i>
                    </div>
                    <div class="widget-data">
                        <div style="font-size: 1.5rem; font-weight: 600;">İletişim</div>
                    </div>
                </div>
            </a>
        </div>
    </div>

</div>



<div class="row">
    <div class="col-xl-3 mb-30">
        <div class="card-box height-100-p widget-style1">
            <a href="@Url.Action("Index", "Feature")" style="text-decoration: none; color: inherit;">
                <div class="d-flex align-items-center justify-content-center" style="height: 100px;">
                    <div class="mr-3 text-danger">
                        <i class="fa fa-feed fa-3x"></i>
                    </div>
                    <div class="widget-data">
                        <div style="font-size: 1.5rem; font-weight: 600;">Öne Çıkanlar</div>
                    </div>
                </div>
            </a>
        </div>
    </div>

    <div class="col-xl-3 mb-30">
        <div class="card-box height-100-p widget-style1">
            <a href="@Url.Action("Index", "Team")" style="text-decoration: none; color: inherit;">
                <div class="d-flex align-items-center justify-content-center" style="height: 100px;">
                    <div class="mr-3 text-info">
                        <i class="fa fa-users fa-3x"></i>
                    </div>
                    <div class="widget-data">
                        <div style="font-size: 1.5rem; font-weight: 600;">Ekibimiz</div>
                    </div>
                </div>
            </a>
        </div>
    </div>

    <div class="col-xl-3 mb-30">
        <div class="card-box height-100-p widget-style1">
            <a href="@Url.Action("Index", "Testimonial")" style="text-decoration: none; color: inherit;">
                <div class="d-flex align-items-center justify-content-center" style="height: 100px;">
                    <div class="mr-3 text-secondary">
                        <i class="fa fa-comment fa-3x"></i>
                    </div>
                    <div class="widget-data">
                        <div style="font-size: 1.5rem; font-weight: 600;">Referanslar</div>
                    </div>
                </div>
            </a>
        </div>
    </div>
</div>

Views/Admin/PartialHead.cshtml
<head>
    <!-- Basic Page Info -->
    <meta charset="utf-8">
    <title>DeskApp - Bootstrap Admin Dashboard HTML Template</title>

    <!-- Site favicon -->
    <link rel="apple-touch-icon" sizes="180x180" href="~/Content/deskapp2-master/vendors/images/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="~/Content/deskapp2-master/vendors/images/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="~/Content/deskapp2-master/vendors/images/favicon-16x16.png">

    <!-- Mobile Specific Metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&display=swap" rel="stylesheet">
    <!-- CSS -->
    <link rel="stylesheet" type="text/css" href="~/Content/deskapp2-master/vendors/styles/core.css">
    <link rel="stylesheet" type="text/css" href="~/Content/deskapp2-master/vendors/styles/icon-font.min.css">
    <link rel="stylesheet" type="text/css" href="~/Content/deskapp2-master/src/plugins/datatables/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" type="text/css" href="~/Content/deskapp2-master/src/plugins/datatables/css/responsive.bootstrap4.min.css">
    <link rel="stylesheet" type="text/css" href="~/Content/deskapp2-master/vendors/styles/style.css">

    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-119386393-1"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag() { dataLayer.push(arguments); }
        gtag('js', new Date());

        gtag('config', 'UA-119386393-1');
    </script>
</head>

Views/Admin/PartialScript.cshtml
<!-- js -->
<script src="~/Content/deskapp2-master/vendors/scripts/core.js"></script>
<script src="~/Content/deskapp2-master/vendors/scripts/script.min.js"></script>
<script src="~/Content/deskapp2-master/vendors/scripts/process.js"></script>
<script src="~/Content/deskapp2-master/vendors/scripts/layout-settings.js"></script>
<script src="~/Content/deskapp2-master/src/plugins/apexcharts/apexcharts.min.js"></script>
<script src="~/Content/deskapp2-master/src/plugins/datatables/js/jquery.dataTables.min.js"></script>
<script src="~/Content/deskapp2-master/src/plugins/datatables/js/dataTables.bootstrap4.min.js"></script>
<script src="~/Content/deskapp2-master/src/plugins/datatables/js/dataTables.responsive.min.js"></script>
<script src="~/Content/deskapp2-master/src/plugins/datatables/js/responsive.bootstrap4.min.js"></script>
<script src="~/Content/deskapp2-master/vendors/scripts/dashboard.js"></script>

Views/Admin/PartialSideBar.cshtml
<div class="left-side-bar">
    <div class="brand-logo">
        <a href="@Url.Action("Index", "Home")">
            <img src="~/Content/deskapp2-master/vendors/images/deskapp-logo.svg" alt="" class="dark-logo">
            <img src="~/Content/deskapp2-master/vendors/images/deskapp-logo-white.svg" alt="" class="light-logo">
        </a>
        <div class="close-sidebar" data-toggle="left-sidebar-close">
            <i class="ion-close-round"></i>
        </div>
    </div>
    <div class="menu-block customscroll">
        <div class="sidebar-menu">
            <ul id="accordion-menu">
                <li>
                    <a href="@Url.Action("Index", "Home")" class="dropdown-toggle no-arrow menu-item">
                        <span class="icon-copy ti-home"></span>
                        <span class="mtext">Ana Sayfa</span>
                    </a>
                </li>
                <li>
                    <a href="@Url.Action("Index", "About")" class="dropdown-toggle no-arrow menu-item">
                        <span class="icon-copy ti-write"></span>
                        <span class="mtext">Hakkımızda</span>
                    </a>
                </li>
                <li>
                    <a href="@Url.Action("GenerateImage", "ServiceImage")" class="dropdown-toggle no-arrow menu-item">
                        <span class="icon-copy ti-receipt"></span>
                        <span class="mtext">Hizmetler</span>
                    </a>
                </li>
                <li>
                    <a href="@Url.Action("Index", "Team")" class="dropdown-toggle no-arrow menu-item">
                        <span class="icon-copy ti-user"></span>
                        <span class="mtext">Ekibimiz</span>
                    </a>
                </li>
                <li>
                    <a href="@Url.Action("Generate", "Faq")" class="dropdown-toggle no-arrow menu-item">
                        <span class="icon-copy ti-comment-alt"></span>
                        <span class="mtext">SSS</span>
                    </a>
                </li>
                <li>
                    <a href=""@Url.Action("Index", "Testimonial")"" class="dropdown-toggle no-arrow menu-item">
                        <span class="icon-copy ti-write"></span>
                        <span class="mtext">Referanslar</span>
                    </a>
                </li>
                <li>
                    <a href=""@Url.Action("Index", "Contact")" class="dropdown-toggle no-arrow menu-item">
                        <span class="icon-copy ti-stats-up"></span>
                        <span class="mtext">İletişim</span>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</div>

<style>
    .menu-item {
        display: flex;
        align-items: center;
        justify-content: flex-start; /* SOLA yasla */
    }

        .menu-item .icon-copy {
            font-size: 23px;
            margin-right: 10px; /* ikon ile yazı arası */
        }

        .menu-item .mtext {
            font-size: 20px;
        }
</style>