Models/ViewModels/TestimonialViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace LifeSure.Models.ViewModels
{
    public class TestimonialViewModel
    {
        public string Name { get; set; }

        public string Title { get; set; }

        public string Comment { get; set; }

        public string Image { get; set; }
    }
}

Controllers/ContactController.cs
using LifeSure.Models.DataModels;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LifeSure.Controllers
{
    public class ContactController : Controller
    {
        private readonly LifeSureDbEntities db = new LifeSureDbEntities();
        public ActionResult Index()
        {
            var contactList = db.TblContact.ToList();
            return View(contactList);
        }

        [HttpGet]
        public ActionResult AddContact()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddContact(TblContact contact)
        {
            if (ModelState.IsValid)
            {
                db.TblContact.Add(contact);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(contact);
        }

        public ActionResult Delete(int id)
        {
            var contact = db.TblContact.Find(id);
            if (contact != null)
            {
                db.TblContact.Remove(contact);
                db.SaveChanges();
            }
            return RedirectToAction("Index", "Admin");
        }

        [HttpGet]
        public ActionResult UpdateContact(int id)
        {
            var contact = db.TblContact.Find(id);
            if (contact == null)
            {
                return HttpNotFound();
            }
            return View(contact);
        }

        [HttpPost]
        public ActionResult UpdateContact(TblContact contact)
        {
            if (ModelState.IsValid)
            {
                db.Entry(contact).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(contact);
        }
    }
}

Controllers/TestimonialController.cs
using LifeSure.Models.DataModels;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LifeSure.Controllers
{
    public class TestimonialController : Controller
    {
        private readonly LifeSureDbEntities db = new LifeSureDbEntities();
        public ActionResult Index()
        {
            var testimonialList = db.TblTestimonial.ToList();
            return View(testimonialList);
        }


        [HttpGet]
        public ActionResult AddTestimonial()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddTestimonial(TblTestimonial testimonial)
        {
            if (ModelState.IsValid)
            {
                db.TblTestimonial.Add(testimonial);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(testimonial);
        }

        public ActionResult Delete(int id)
        {
            var testimonial = db.TblTestimonial.Find(id);
            if (testimonial != null)
            {
                db.TblTestimonial.Remove(testimonial);
                db.SaveChanges();
            }
            return RedirectToAction("Index", "Admin");
        }

        [HttpGet]
        public ActionResult UpdateTestimonial(int id)
        {
            var testimonial = db.TblTestimonial.Find(id);
            if (testimonial == null)
            {
                return HttpNotFound();
            }
            return View(testimonial);
        }

        [HttpPost]
        public ActionResult UpdateTestimonial(TblTestimonial testimonial)
        {
            if (ModelState.IsValid)
            {
                db.Entry(testimonial).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(testimonial);
        }
    }
}

Views/Testimonial/Index.cshtml
@model IEnumerable<LifeSure.Models.DataModels.TblTestimonial>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="pd-20 card-box mb-30">
    <div class="clearfix mb-20">
        <div class="pull-left">
            <h4 class="text-blue h4">Referans Listesi</h4>
        </div>
        <div class="pull-right">
            <a href="@Url.Action("AddTestimonial", "Testimonial")" class="btn btn-success btn-sm">
                <i class="fa fa-plus"></i> Yeni Ekle
            </a>
        </div>
    </div>
    <table class="table">
        <thead>
            <tr>
                <th>#</th>
                <th>Ad Soyad</th>
                <th>Başlık</th>
                <th>Yorum</th>
                <th>Görsel URL</th>
                <th>Sil</th>
                <th>Güncelle</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.TestimonialId</td>
                    <td>@item.Name</td>
                    <td>@item.Title</td>
                    <td>@item.Comment</td>
                    <td>@item.ImageUrl</td>
                    <td>
                        <a href="@Url.Action("Delete", "Contact", new { id = item.TestimonialId })" class="btn btn-danger btn-sm">
                            <i class="fa fa-trash"></i> Sil
                        </a>

                    </td>
                    <td>
                        <a href="@Url.Action("UpdateContact", "Contact", new { id = item.TestimonialId })" class="btn btn-warning btn-sm">
                            <i class="fa fa-edit"></i> Güncelle
                        </a>

                    </td>
                </tr>
            }
        </tbody>

    </table>
</div>