Controllers/FeatureController.cs
using LifeSure.Models.DataModels;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LifeSure.Controllers
{
    public class FeatureController : Controller
    {
        private readonly LifeSureDbEntities db = new LifeSureDbEntities();
        public ActionResult Index()
        {
            var featureList = db.TblFeature.ToList();
            return View(featureList);
        }

        [HttpGet]
        public ActionResult AddFeature()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddFeature(TblFeature feature)
        {
            if (ModelState.IsValid)
            {
                db.TblFeature.Add(feature);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(feature);
        }

        public ActionResult Delete(int id)
        {
            var feature = db.TblFeature.Find(id);
            if (feature != null)
            {
                db.TblFeature.Remove(feature);
                db.SaveChanges();
            }
            return RedirectToAction("Index", "Admin");
        }

        [HttpGet]
        public ActionResult UpdateFeature(int id)
        {
            var feature = db.TblFeature.Find(id);
            if (feature == null)
            {
                return HttpNotFound();
            }
            return View(feature);
        }

        [HttpPost]
        public ActionResult UpdateFeature(TblFeature feature)
        {
            if (ModelState.IsValid)
            {
                db.Entry(feature).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(feature);
        }
    }
}

Views/Feature/Index.cshtml
@model IEnumerable<LifeSure.Models.DataModels.TblFeature>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="pd-20 card-box mb-30">
    <div class="clearfix mb-20">
        <div class="pull-left">
            <h4 class="text-blue h4">Öne Çıkanlar</h4>
        </div>
        <div class="pull-right">
            <a href="@Url.Action("AddFeature", "Feature")" class="btn btn-success btn-sm">
                <i class="fa fa-plus"></i> Yeni Ekle
            </a>
        </div>
    </div>
    <table class="table">
        <thead>
            <tr>
                <th>#</th>
                <th>Başlık</th>
                <th>Açıklama</th>
                <th>İkon</th>
                <th>Sil</th>
                <th>Güncelle</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.FeatureId</td>
                    <td>@item.Title</td>
                    <td>@item.Description</td>
                    <td>@item.Icon</td>
                    <td>
                        <a href="@Url.Action("Delete", "Feature", new { id = item.FeatureId })" class="btn btn-danger btn-sm">
                            <i class="fa fa-trash"></i> Sil
                        </a>

                    </td>
                    <td>
                        <a href="@Url.Action("UpdateFeature", "Feature", new { id = item.FeatureId })" class="btn btn-warning btn-sm">
                            <i class="fa fa-edit"></i> Güncelle
                        </a>

                    </td>
                </tr>
            }
        </tbody>

    </table>
</div>